spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    com.erp.manufacturing: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
